### ISSUE TITLE
No Hosts, No Services

### ISSUE THREAD

**Issue by matthieu-robin** [centreon/nagiosToCentreon#2]
I have tested and i don't have any details of:
- hosts
- services
- templates
- ...

I've got only : 
- contacts
- contact groups
- commands
- time period

is it expected? :-)

Thanks

**Comment by lpinsivy** [comment]
Maybe due to issue #1 

I have all information

HOST;ADD;c****_**9;BO Test;172.__._**.129;host-server;Central;
HOST;setparam;c******_9;active_checks_enabled;1
HOST;setparam;c**_***_9;check_command;check_host_icmp_alive
HOST;setparam;c**_***_9;check_interval;5
HOST;setparam;c**_***_9;check_period;24x7
HOST;setparam;c**_***_9;event_handler_enabled;1
HOST;setparam;c**_***_9;flap_detection_enabled;1
HOST;setparam;c**_***_9;max_check_attempts;5
HOST;setparam;c**_***_9;notifications_enabled;1
HOST;setparam;c**_***_9;notification_interval;1440
HOST;setparam;c**_***_9;notification_options;d,u,r
HOST;setparam;c**_***_9;notification_period;24x7
HOST;setparam;c**_***_9;process_perf_data;1
HOST;setparam;c**_***_9;retain_nonstatus_information;0
HOST;setparam;c**_***_9;retain_status_information;1
HOST;setparam;c**_***_9;retry_check_interval;1
HOST;addcontactgroup;c**_***_9;grp_t**_
